language: generic
services:
  - docker

before_install:
  - docker build -t trebu2002/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true trebu2002/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-792648339719"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
